### ISSUE TITLE
Special characters in name

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/CEPGP_BulkAward#1]
![bild](https://user-images.githubusercontent.com/288724/98230870-f4887280-1f5b-11eb-9c4c-888d1d0dcda1.png)

Leaves error player not found

**Comment by gstorer** [comment]
This happens because lua has pretty average support for unicode.

%a only matches regular characters in this line:
 `player, amount, msg = string.match(ln, "(%a+),(-?%d+),(.*)")`

If you use the function used be the CEPGP import it should work (disclaimer: not really tested):
```
local split = CEPGP_split(ln,",")
player = split[1]
amount = split[2]
msg = split[3]
```

It would be awesome if you could make another real with this fix :)

**Comment by kvakvs** [comment]
It works, let me update it then
